-- Registro automático das alterações realizadas pelos administradores.
-- Execute uma única vez no SQL Editor do Supabase, depois da migração 019.

create table if not exists public.admin_activity_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references auth.users(id) on delete set null,
  admin_email text,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  entity_type text not null,
  record_id text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_activity_logs_created_at_idx
on public.admin_activity_logs (created_at desc);

create index if not exists admin_activity_logs_entity_idx
on public.admin_activity_logs (entity_type, created_at desc);

alter table public.admin_activity_logs enable row level security;

drop policy if exists "Admins can read activity logs" on public.admin_activity_logs;
create policy "Admins can read activity logs"
on public.admin_activity_logs for select
to authenticated
using (public.is_admin());

revoke all on public.admin_activity_logs from anon;
revoke insert, update, delete on public.admin_activity_logs from authenticated;
grant select on public.admin_activity_logs to authenticated;

create or replace function public.log_admin_activity()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  actor_id uuid := auth.uid();
  actor_email text;
  previous_row jsonb;
  current_row jsonb;
  affected_id text;
begin
  -- A auditoria registra somente ações feitas por uma sessão administrativa.
  if actor_id is null or not public.is_admin() then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  select email into actor_email
  from auth.users
  where id = actor_id;

  previous_row := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  current_row := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
  affected_id := coalesce(current_row ->> 'id', previous_row ->> 'id');

  -- Tabelas com chave composta não possuem uma coluna id.
  if affected_id is null then
    affected_id := concat_ws(':',
      coalesce(current_row ->> 'round_id', previous_row ->> 'round_id'),
      coalesce(current_row ->> 'game_id', previous_row ->> 'game_id'),
      coalesce(current_row ->> 'player_id', previous_row ->> 'player_id'),
      coalesce(current_row ->> 'category', previous_row ->> 'category')
    );
  end if;

  insert into public.admin_activity_logs (
    admin_user_id,
    admin_email,
    action,
    entity_type,
    record_id,
    old_data,
    new_data
  ) values (
    actor_id,
    actor_email,
    tg_op,
    tg_table_name,
    nullif(affected_id, ''),
    previous_row,
    current_row
  );

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

revoke all on function public.log_admin_activity() from public;

do $$
declare
  audited_table text;
begin
  foreach audited_table in array array[
    'players',
    'rounds',
    'games',
    'player_game_stats',
    'player_season_adjustments',
    'round_attendance',
    'round_awards',
    'game_goal_events',
    'bulletin_notices'
  ]
  loop
    if to_regclass('public.' || audited_table) is not null then
      execute format('drop trigger if exists audit_admin_changes on public.%I', audited_table);
      execute format(
        'create trigger audit_admin_changes after insert or update or delete on public.%I for each row execute function public.log_admin_activity()',
        audited_table
      );
    end if;
  end loop;
end;
$$;
